# Generated by Django 3.1.5 on 2021-03-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupForm',
            fields=[
                ('SignupFormId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=100)),
                ('Email', models.EmailField(default='', max_length=100)),
                ('Mobile_Number', models.CharField(default='', max_length=200)),
                ('Gender', models.CharField(default='', max_length=255)),
                ('Question_1', models.CharField(default='', max_length=255)),
                ('Question_2', models.CharField(default='', max_length=255)),
                ('Question_3', models.CharField(default='', max_length=255)),
                ('Question_4', models.CharField(default='', max_length=255)),
                ('Question_5', models.CharField(default='', max_length=255)),
                ('Question_6', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
